### ISSUE TITLE
All buttons are not rendered correctly.

### ISSUE THREAD

**Issue by 1yefuwang1** [plantain-00/schema-based-json-editor#11]
#### Expected:
Buttons in the vue.js example are rendered correctly. For instance, the `collapse` button that comes with the `arrayExample` is rendered as follows.
![image](https://user-images.githubusercontent.com/18023393/37642926-e51d9688-2c59-11e8-8e89-f329344299c4.png)

#### Actual: 
When playing with this library, my buttons are not rendered correctly.
![image](https://user-images.githubusercontent.com/18023393/37643013-316f6930-2c5a-11e8-85c0-e77f345cbe53.png)
So visually, all buttons are not visible on the rendered page.

**Comment by plantain-00** [comment]
Can you try `icon=undefined`? It seems `icon=null` is not handled correctly.

**Comment by 1yefuwang1** [comment]
After changing icon to 'element-ui2', the rendered buttons are as follows.
![image](https://user-images.githubusercontent.com/18023393/37645803-d027ddca-2c62-11e8-87eb-e68124b81050.png)
Whereas the same configuration in the demo gives me:
![image](https://user-images.githubusercontent.com/18023393/37646132-bf12b0ae-2c63-11e8-9a72-bb0f642f44d6.png)

I don't have much insights to offer, but the following things are worth mentioning:

1. The magic number `data-v-5cf26f6a` keeps popping up.
2. The value of `text` attribute is definitely wrongly rendered.

**Comment by plantain-00** [comment]
I haven't meet this problem, can you provide a reproducible demo about this? a jsfiddle one is enough.

**Comment by 1yefuwang1** [comment]
I'm trying to reproduce, but having trouble to get this component working with `jsfiddle`. Can you please provide a working `jsfiddle` example?  Or could you please make the following `jsfiddle` session working?
[https://jsfiddle.net/1yefuwang1/50wL7mdz/209952/#&togetherjs=HNGvDLo34u](here)

**Comment by plantain-00** [comment]
This one is good to go: https://jsfiddle.net/ujz15hr9/1/

The document shows how to use it as script tags: https://github.com/plantain-00/schema-based-json-editor#vuejs-component

**Comment by 1yefuwang1** [comment]
I have found the bug. It seems my vue project has a globally registered component named 'icon', which  happens to share the same name of the button component of this library('icon').
