### ISSUE TITLE
making a field read only

### ISSUE THREAD

**Issue by shagabay** [plantain-00/schema-based-json-editor#14]
hi,

i hope to be able to contribute some day :) i see all those "help wanted" but haven't mastered the source well enough, hope to do so soon.

regarding a field that has an initial value which i don't want to be changed, i know there's such a flag in the editor, but can it be accessed here?

thanks a lot
sharon

**Comment by plantain-00** [comment]
`readonly` is supported now: https://github.com/plantain-00/schema-based-json-editor#features
> common schema fields: title, description, default, readonly, propertyOrder, requiredWhen('===', 'in')

Is this what you want?

**Comment by shagabay** [comment]
works perfect, thanks!
