### ISSUE TITLE
itemTitle: item title is not updated for newly added  items in list

### ISSUE THREAD

**Issue by DomasM** [plantain-00/schema-based-json-editor#21]
#### Version(if relevant): 1.0.0
7.5.0
#### Environment(if relevant):
vue 2.6.10
#### Code(if relevant):
[see vue demo in you readme](https://plantain-00.github.io/schema-based-json-editor/packages/vue/demo/)

See section itemTitleExample with items having property propertyExample1 set to 'foo', 'bar' and so on.
#### Expected:
When I add new item and change propertyExample1, itemTitle updates, jsut as it does for old items
#### Actual:
itemTitle is just the index in the array and does not update

![image](https://user-images.githubusercontent.com/13480638/56041362-35e57b80-5d41-11e9-822e-cba6a69d6823.png)

**Comment by plantain-00** [comment]
v7.20.3 should fix this

**Comment by DomasM** [comment]
Cool, thanks.
