### ISSUE TITLE
how to hide or remove 'not exists' checkbox.

### ISSUE THREAD

**Issue by Rajkapoor1** [plantain-00/schema-based-json-editor#25]
#### Environment(if relevant):
I'm using angular verrsion 8.0.0

#### Code(if relevant):
<json-editor [schema]="schema"
    [initialValue]="value"
   
    theme="bootstrap3"
    icon="fontawesome4">
</json-editor>

in appcomponent.ts file, I have defined schema object as below
schema = {
      type : 'object',
      title: 'schema generator',
      description: 'dfdfd',
      properties: {
          stringExample : {
            type: 'string',
           title: 'A string example',
          description: 'a string description',
          default: 'a default string example',
          minLength: 15,
          maxLength: 20,
          propertyOrder: 1
          },
          stringExample1 : {
            type: 'string',
           title: 'Name',
          description: 'Name',
          default: 'Rajesh',
          minLength: 15,
          maxLength: 20,
          propertyOrder: 2
          }
          }
      };
```
here I'm expecting to show only 2 text boxes but after executing above code, in addition with textboxes, it shows 2 checkboxes and 1 button control. 
checkboxes which has caption 'not exists' . Basically it toggles the other textbox visibility. 
is there any way to hide or unshow this checkbox and directly shows textboxes?

**Comment by plantain-00** [comment]
Can you try to add `"required": ["stringExample"]`

**Comment by Rajkapoor1** [comment]
Hi,
I tried by adding required in below schema but still, it shows checkboxes.
schema = {
    type : 'object',
    title: 'schema generator',
    description: 'dfdfd',
    properties: {
        stringExample : {
            type: 'string',
            title: 'A string example',
            description: 'a string description',
            default: 'a default string example',
            minLength: 15,
            maxLength: 20,
            propertyOrder: 1
        },
        stringExample1 : {
            type: 'string',
            title: 'Name',
            description: 'Name',
            default: 'danial',
            minLength: 15,
            maxLength: 20,
            propertyOrder: 2
        },
        required: ['stringExample']
    }
};
not sure what I'm missing here.

**Comment by Rajkapoor1** [comment]
![image](https://user-images.githubusercontent.com/55281556/64870783-90249880-d661-11e9-8fd3-d5f886a3eaca.png)

**Comment by Rajkapoor1** [comment]
above is output which shows 'not exists' checkboxes.

**Comment by plantain-00** [comment]
```json
{
  "type": "object",
  "title": "schema generator",
  "description": "dfdfd",
  "properties": {
    "stringExample": {
      "type": "string",
      "title": "A string example",
      "description": "a string description",
      "default": "a default string example",
      "minLength": 15,
      "maxLength": 20,
      "propertyOrder": 1
    },
    "stringExample1": {
      "type": "string",
      "title": "Name",
      "description": "Name",
      "default": "danial",
      "minLength": 15,
      "maxLength": 20,
      "propertyOrder": 2
    }
  },
  "required": [
    "stringExample"
  ]
}
```

**Comment by Rajkapoor1** [comment]
Thanks a lot, it works.
is there any way to set the text to the button which expand/collapse the elements? button which shows in above, below 'schema generator' text.?

**Comment by plantain-00** [comment]
It seems you set `icon="fontawesome4"`, but didn't load font awesome 4.
Or just remove `icon` property, its optional.

**Comment by Rajkapoor1** [comment]
Thanks a lot, it works.
