### ISSUE TITLE
No style is applied

### ISSUE THREAD

**Issue by bayerlse** [plantain-00/schema-based-json-editor#33]
#### Version: 
8.2.1

#### Code:

```
<JSONEditor
                schema={schema}
                initialValue={content}
                updateValue={() => console.log('UPDATED')}
                theme="bootstrap3"
                icon="bootstrap3"
            />
```

#### Expected:

bootstrap3 styles are applied

#### Actual:

bootstrap3 styles are not applied, despite bootstrap css is included on page. 
Do you have any example how the styling can be applied in react app?
Thanks!

**Comment by plantain-00** [comment]
You can check whether the class is `well schema-based-json-editor--card` for boostrap3, and whether they are loaded from `bootstrap.min.css`
![屏幕快照 2021-03-13 19 30 10](https://user-images.githubusercontent.com/7639395/111028599-8df7f180-8432-11eb-8235-1db6909345fc.png)

**Comment by bayerlse** [comment]
Thanks for the quick reply! They indeed were'nt loaded.
