### ISSUE TITLE
Array without index titles?

### ISSUE THREAD

**Issue by tonisimakov99** [plantain-00/schema-based-json-editor#38]
How to hide array titles?

**Comment by plantain-00** [comment]
Maybe add `display: none` for class `schema-based-json-editor--title`

**Comment by tonisimakov99** [comment]
> Maybe add `display: none` for class `schema-based-json-editor--title`

it's hide all titles on all controls, need for array only

**Comment by plantain-00** [comment]
Maybe add `className` in array schema, then set styles for it.
