### ISSUE TITLE
'MarkdownIt' only refers to a type, but is being used as a value here

### ISSUE THREAD

**Issue by hectorj** [plantain-00/schema-based-json-editor#4]
Hi!

Trying `schema-based-json-editor` version 5.1.2, I get an error when compiling my TypeScript:

```
 error  in /path/to/my/project/node_modules/schema-based-json-editor/libs.d.ts

(8,37): error TS2693: 'MarkdownIt' only refers to a type, but is being used as a value here.
```

According to my package-lock.json, my version of `@types/markdown-it` is 0.0.4 (as required).

I'm still a beginner with TypeScript so I don't really know where that is coming from.

**Comment by plantain-00** [comment]
you can set `"skipLibCheck": true` in tsconfig.json to disable the error for now, and I will fix this later.

**Comment by plantain-00** [comment]
v5.1.4 should fix this

**Comment by hectorj** [comment]
Fixed indeed, thanks a lot!
