### ISSUE TITLE
support vue2

### ISSUE THREAD

**Issue by brianjcj** [plantain-00/schema-based-json-editor#40]
is it possible to support vue2 so that my old vue2 based project can use it :-)

**Comment by plantain-00** [comment]
vue2 support is on v7.25.2: https://github.com/plantain-00/schema-based-json-editor/tree/vue2#vuejs-component

**Comment by brianjcj** [comment]
> vue2 support is on v7.25.2: https://github.com/plantain-00/schema-based-json-editor/tree/vue2#vuejs-component

Thank you so much!

**Comment by brianjcj** [comment]
already done.
